-- Reference DDL: exchange_price_feed
-- Phase 43: Exchange Integration
--
-- Stores spot price snapshots fetched from exchange REST APIs.
-- Compared against bar close prices from price_bars_multi_tf to detect
-- stale data or significant price divergences.
--
-- Authoritative migration: alembic/versions/b180d8d07a85_exchange_tables.py
-- This file is a human-readable reference only.

CREATE TABLE IF NOT EXISTS public.exchange_price_feed (
    -- Primary key: UUID generated by the application at fetch time
    feed_id         UUID        NOT NULL,

    -- When the snapshot was fetched from the exchange
    fetched_at      TIMESTAMPTZ NOT NULL,

    -- Source exchange (allowed values enforced by CHECK constraint below)
    exchange        TEXT        NOT NULL,

    -- Trading pair as used by the exchange (e.g. 'BTC-USD', 'BTCUSD', 'XBT/USD')
    pair            TEXT        NOT NULL,

    -- Whether this snapshot was taken against the sandbox or production API
    environment     TEXT        NOT NULL DEFAULT 'sandbox',

    -- Live prices from the exchange ticker endpoint
    bid_price       NUMERIC,
    ask_price       NUMERIC,
    mid_price       NUMERIC,
    last_price      NUMERIC,

    -- Most recent bar close from price_bars_multi_tf used for comparison
    bar_close       NUMERIC,
    bar_ts          TIMESTAMPTZ,

    -- Discrepancy: (mid_price - bar_close) / bar_close, expressed as a fraction
    discrepancy_pct NUMERIC,

    -- Adaptive threshold at fetch time (scaled from asset_stats.std_ret_30)
    threshold_pct   NUMERIC,

    -- TRUE when ABS(discrepancy_pct) > threshold_pct
    exceeds_threshold BOOLEAN,

    -- Audit timestamp
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT pk_exchange_price_feed PRIMARY KEY (feed_id),
    CONSTRAINT chk_price_feed_exchange
        CHECK (exchange IN ('coinbase', 'kraken', 'binance', 'bitfinex', 'bitstamp'))
);

-- Composite index for time-series queries: exchange + pair scans ordered by time
CREATE INDEX IF NOT EXISTS idx_price_feed_exchange_pair_ts
    ON public.exchange_price_feed (exchange, pair, fetched_at DESC);

-- Partial index for threshold alert queries -- only indexes flagged rows
CREATE INDEX IF NOT EXISTS idx_price_feed_exceeds_threshold
    ON public.exchange_price_feed (exchange, pair, fetched_at)
    WHERE exceeds_threshold = TRUE;
