-- Reference DDL: paper_orders
-- Phase 43: Exchange Integration
--
-- Lightweight log of paper orders translated from cmc_signals rows.
-- Records the canonical order format plus the per-exchange JSON payload
-- that WOULD be sent to the real REST API.
--
-- Status lifecycle for Phase 43: 'paper' only.
-- Phase 44 may extend to 'pending', 'filled', 'cancelled', 'rejected' for
-- live order management.
--
-- Authoritative migration: alembic/versions/b180d8d07a85_exchange_tables.py
-- This file is a human-readable reference only.

CREATE TABLE IF NOT EXISTS public.paper_orders (
    -- Primary key: UUID generated by the application at order creation time
    order_uuid      UUID        NOT NULL,

    -- When the paper order was created
    created_at      TIMESTAMPTZ NOT NULL,

    -- FK-like references (not enforced as FK to keep the table standalone)
    signal_id       INTEGER,
    asset_id        INTEGER,

    -- Order routing
    exchange        TEXT        NOT NULL,
    pair            TEXT        NOT NULL,

    -- Order parameters
    side            TEXT        NOT NULL,    -- 'buy' | 'sell'
    order_type      TEXT        NOT NULL,    -- 'market' | 'limit' | 'stop' | 'stop_limit'
    quantity        NUMERIC     NOT NULL,
    limit_price     NUMERIC,                 -- NULL for market orders
    stop_price      NUMERIC,                 -- NULL unless stop or stop_limit

    -- JSON payload that would be sent to the exchange REST API.
    -- Format is exchange-specific (Coinbase vs Kraken differ significantly).
    exchange_payload TEXT,

    -- Lifecycle status
    status          TEXT        NOT NULL DEFAULT 'paper',

    -- Whether this order was created against the sandbox or production API
    environment     TEXT        NOT NULL DEFAULT 'sandbox',

    -- Client-side idempotency key for deduplication
    client_order_id TEXT,

    -- Audit timestamp
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Constraints
    CONSTRAINT pk_paper_orders PRIMARY KEY (order_uuid),
    CONSTRAINT chk_paper_orders_side
        CHECK (side IN ('buy', 'sell')),
    CONSTRAINT chk_paper_orders_order_type
        CHECK (order_type IN ('market', 'limit', 'stop', 'stop_limit')),
    CONSTRAINT chk_paper_orders_status
        CHECK (status IN ('paper', 'pending', 'filled', 'cancelled', 'rejected'))
);

-- Index for asset + time queries (dashboard / reporting)
CREATE INDEX IF NOT EXISTS idx_paper_orders_asset_id_ts
    ON public.paper_orders (asset_id, created_at);

-- Index for signal tracing -- find all paper orders that originated from a given signal
CREATE INDEX IF NOT EXISTS idx_paper_orders_signal_id
    ON public.paper_orders (signal_id);
