"""exchange_tables

Revision ID: b180d8d07a85
Revises: e74f5622e710
Create Date: 2026-02-24 22:31:06.788646

Creates 2 tables for Phase 43 (Exchange Integration):

exchange_price_feed:
  Stores spot price snapshots fetched from exchange APIs, compared against
  the bar data stored in cmc_price_bars_multi_tf. Records bid/ask/mid/last
  prices plus discrepancy metrics vs the most recent bar close.
  CHECK constraint limits exchange to known venues.
  Indexes support time-series queries and threshold alert queries.

paper_orders:
  Lightweight log of paper orders translated from cmc_signals rows.
  Records the canonical order format plus the per-exchange JSON payload
  that WOULD be sent to the real API. Status lifecycle: 'paper' only
  (Phase 44 adds live fill tracking).
  CHECK constraints enforce allowed values for side, order_type, status.

All tables use schema="public".
No UTF-8 box-drawing characters to avoid Windows cp1252 decode errors.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b180d8d07a85"
down_revision: Union[str, Sequence[str], None] = "e74f5622e710"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Known exchange values enforced by CHECK constraint
_EXCHANGES = ("coinbase", "kraken", "binance", "bitfinex", "bitstamp")
_EXCHANGE_CHECK = "exchange IN (" + ", ".join(f"'{e}'" for e in _EXCHANGES) + ")"


def upgrade() -> None:
    """Upgrade schema: create exchange_price_feed and paper_orders tables."""

    # ------------------------------------------------------------------
    # Table: exchange_price_feed
    # Spot price snapshots fetched from exchange REST APIs.
    # PK: feed_id (UUID, generated by application)
    # ------------------------------------------------------------------
    op.create_table(
        "exchange_price_feed",
        # Primary key
        sa.Column("feed_id", sa.UUID(), nullable=False),
        # When the snapshot was fetched
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        # Source exchange and trading pair (e.g. 'BTC-USD', 'XBT/USD')
        sa.Column("exchange", sa.Text(), nullable=False),
        sa.Column("pair", sa.Text(), nullable=False),
        # Sandbox vs production flag -- allows storing both in same table
        sa.Column("environment", sa.Text(), nullable=False, server_default="sandbox"),
        # Live prices from the exchange ticker
        sa.Column("bid_price", sa.Numeric(), nullable=True),
        sa.Column("ask_price", sa.Numeric(), nullable=True),
        sa.Column("mid_price", sa.Numeric(), nullable=True),
        sa.Column("last_price", sa.Numeric(), nullable=True),
        # Reference bar data for discrepancy comparison
        sa.Column("bar_close", sa.Numeric(), nullable=True),
        sa.Column("bar_ts", sa.DateTime(timezone=True), nullable=True),
        # Discrepancy metrics: (mid_price - bar_close) / bar_close
        sa.Column("discrepancy_pct", sa.Numeric(), nullable=True),
        # Adaptive threshold used at fetch time (scaled from cmc_asset_stats.std_ret_30)
        sa.Column("threshold_pct", sa.Numeric(), nullable=True),
        # Flag set TRUE when abs(discrepancy_pct) > threshold_pct
        sa.Column("exceeds_threshold", sa.Boolean(), nullable=True),
        # Audit timestamp
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Constraints
        sa.PrimaryKeyConstraint("feed_id"),
        sa.CheckConstraint(
            _EXCHANGE_CHECK,
            name="chk_price_feed_exchange",
        ),
        schema="public",
    )

    # Composite index for time-series queries: exchange + pair scans ordered by time
    op.create_index(
        "idx_price_feed_exchange_pair_ts",
        "exchange_price_feed",
        ["exchange", "pair", "fetched_at"],
        schema="public",
        postgresql_ops={"fetched_at": "DESC"},
    )

    # Partial index for threshold alert queries -- only indexes flagged rows
    op.create_index(
        "idx_price_feed_exceeds_threshold",
        "exchange_price_feed",
        ["exchange", "pair", "fetched_at"],
        schema="public",
        postgresql_where=sa.text("exceeds_threshold = TRUE"),
    )

    # ------------------------------------------------------------------
    # Table: paper_orders
    # Log of paper orders translated from signal rows.
    # PK: order_uuid (UUID, generated by application)
    # ------------------------------------------------------------------
    op.create_table(
        "paper_orders",
        # Primary key
        sa.Column("order_uuid", sa.UUID(), nullable=False),
        # Creation timestamp
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        # FK-like references (not enforced as FK to keep table standalone)
        sa.Column("signal_id", sa.Integer(), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        # Order routing
        sa.Column("exchange", sa.Text(), nullable=False),
        sa.Column("pair", sa.Text(), nullable=False),
        # Order parameters
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("order_type", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Numeric(), nullable=False),
        sa.Column("limit_price", sa.Numeric(), nullable=True),
        sa.Column("stop_price", sa.Numeric(), nullable=True),
        # Serialized JSON payload that would be sent to the exchange REST API
        sa.Column("exchange_payload", sa.Text(), nullable=True),
        # Lifecycle status
        sa.Column("status", sa.Text(), nullable=False, server_default="paper"),
        # Sandbox vs production flag
        sa.Column("environment", sa.Text(), nullable=False, server_default="sandbox"),
        # Idempotency key set by the client (useful for deduplication)
        sa.Column("client_order_id", sa.Text(), nullable=True),
        # Audit timestamp
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # Constraints
        sa.PrimaryKeyConstraint("order_uuid"),
        sa.CheckConstraint(
            "side IN ('buy', 'sell')",
            name="chk_paper_orders_side",
        ),
        sa.CheckConstraint(
            "order_type IN ('market', 'limit', 'stop', 'stop_limit')",
            name="chk_paper_orders_order_type",
        ),
        sa.CheckConstraint(
            "status IN ('paper', 'pending', 'filled', 'cancelled', 'rejected')",
            name="chk_paper_orders_status",
        ),
        schema="public",
    )

    # Index for asset + time queries (dashboard / reporting)
    op.create_index(
        "idx_paper_orders_asset_id_ts",
        "paper_orders",
        ["asset_id", "created_at"],
        schema="public",
    )

    # Index for signal tracing -- find all orders from a given signal
    op.create_index(
        "idx_paper_orders_signal_id",
        "paper_orders",
        ["signal_id"],
        schema="public",
    )


def downgrade() -> None:
    """Downgrade schema: drop indexes then tables in reverse order."""

    # Drop paper_orders indexes then table
    op.drop_index(
        "idx_paper_orders_signal_id", table_name="paper_orders", schema="public"
    )
    op.drop_index(
        "idx_paper_orders_asset_id_ts", table_name="paper_orders", schema="public"
    )
    op.drop_table("paper_orders", schema="public")

    # Drop exchange_price_feed indexes then table
    op.drop_index(
        "idx_price_feed_exceeds_threshold",
        table_name="exchange_price_feed",
        schema="public",
    )
    op.drop_index(
        "idx_price_feed_exchange_pair_ts",
        table_name="exchange_price_feed",
        schema="public",
    )
    op.drop_table("exchange_price_feed", schema="public")
