"""
PaperOrderLogger: Writes paper orders to the paper_orders table.

Provides log_order() for single order persistence and log_orders_batch() for
bulk logging. Uses NullPool engine and resolve_db_url() matching project pattern.

Usage:
    logger = PaperOrderLogger()
    order = CanonicalOrder("BTC/USD", "buy", "market", 0.01)
    order_uuid = logger.log_order(order, "coinbase")
"""

from __future__ import annotations

import json
import logging
from typing import List, Optional

from sqlalchemy import text
from sqlalchemy import create_engine
from sqlalchemy.pool import NullPool

from ta_lab2.scripts.refresh_utils import resolve_db_url

logger = logging.getLogger(__name__)


class PaperOrderLogger:
    """
    Persists paper orders to the paper_orders table.

    All orders are logged with status='paper' (simulation, not live execution).
    The exchange_payload column stores the exchange-specific wire format as JSON text.
    """

    def __init__(self, db_url: Optional[str] = None) -> None:
        """
        Initialize PaperOrderLogger.

        Args:
            db_url: Database URL. If None, resolved via resolve_db_url()
                    (checks db_config.env, then TARGET_DB_URL, MARKETDATA_DB_URL env vars).
        """
        if db_url is None:
            db_url = resolve_db_url()
        self._db_url = db_url
        self._engine = create_engine(db_url, poolclass=NullPool)

    def log_order(
        self,
        order: "CanonicalOrder",  # noqa: F821 -- circular import avoided by string annotation
        exchange: str,
        environment: str = "sandbox",
    ) -> str:
        """
        Validate and persist a single paper order.

        Calls order.validate() first, translates to exchange wire format,
        serializes exchange_payload as JSON text, inserts into paper_orders table.

        Args:
            order: CanonicalOrder to log.
            exchange: Exchange name ("coinbase" or "kraken").
            environment: "sandbox" or "production" (default: "sandbox").

        Returns:
            order_uuid as string (UUID generated by DB default).

        Raises:
            ValueError: if order.validate() fails or exchange is unknown.
            sqlalchemy.exc.SQLAlchemyError: on DB write failure.
        """
        # Validate order consistency before any DB work
        order.validate()

        # Translate to exchange wire format and serialize
        exchange_payload = order.to_exchange(exchange)
        exchange_payload_json = json.dumps(exchange_payload)

        sql = text(
            """
            INSERT INTO paper_orders (
                signal_id, asset_id, exchange, pair, side, order_type,
                quantity, limit_price, stop_price, exchange_payload,
                status, environment, client_order_id
            )
            VALUES (
                :signal_id, :asset_id, :exchange, :pair, :side, :order_type,
                :quantity, :limit_price, :stop_price, :exchange_payload,
                'paper', :environment, :client_order_id
            )
            RETURNING order_uuid
            """
        )

        params = {
            "signal_id": order.signal_id,
            "asset_id": order.asset_id,
            "exchange": exchange.lower(),
            "pair": order.pair,
            "side": order.side,
            "order_type": order.order_type,
            "quantity": order.quantity,
            "limit_price": order.limit_price,
            "stop_price": order.stop_price,
            "exchange_payload": exchange_payload_json,
            "environment": environment,
            "client_order_id": order.client_order_id,
        }

        with self._engine.connect() as conn:
            result = conn.execute(sql, params)
            conn.commit()
            row = result.fetchone()
            order_uuid = str(row[0])

        logger.info(
            "Paper order logged: %s %s %s %s on %s (uuid=%s)",
            order.pair,
            order.side,
            order.order_type,
            order.quantity,
            exchange,
            order_uuid,
        )
        return order_uuid

    def log_orders_batch(
        self,
        orders: List["CanonicalOrder"],  # noqa: F821
        exchange: str,
        environment: str = "sandbox",
    ) -> List[str]:
        """
        Log multiple paper orders, returning list of order_uuids.

        Each order is logged individually via log_order(). Failures on individual
        orders propagate immediately (no partial-batch semantics).

        Args:
            orders: List of CanonicalOrder instances to log.
            exchange: Exchange name for all orders.
            environment: "sandbox" or "production" (default: "sandbox").

        Returns:
            List of order_uuid strings in the same order as input.
        """
        uuids = []
        for order in orders:
            uuid_str = self.log_order(order, exchange, environment=environment)
            uuids.append(uuid_str)

        logger.info("Logged %d paper orders on %s", len(uuids), exchange)
        return uuids

    def get_recent_orders(
        self,
        exchange: Optional[str] = None,
        limit: int = 20,
    ) -> list:
        """
        Retrieve recent paper orders, optionally filtered by exchange.

        Args:
            exchange: Exchange name to filter on (None = all exchanges).
            limit: Maximum rows to return (default 20).

        Returns:
            List of dicts with paper_orders row data.
        """
        if exchange is not None:
            sql = text(
                """
                SELECT order_uuid, created_at, signal_id, asset_id, exchange, pair,
                       side, order_type, quantity, limit_price, stop_price,
                       exchange_payload, status, environment, client_order_id
                FROM paper_orders
                WHERE exchange = :exchange
                ORDER BY created_at DESC
                LIMIT :limit
                """
            )
            params: dict = {"exchange": exchange.lower(), "limit": limit}
        else:
            sql = text(
                """
                SELECT order_uuid, created_at, signal_id, asset_id, exchange, pair,
                       side, order_type, quantity, limit_price, stop_price,
                       exchange_payload, status, environment, client_order_id
                FROM paper_orders
                ORDER BY created_at DESC
                LIMIT :limit
                """
            )
            params = {"limit": limit}

        with self._engine.connect() as conn:
            result = conn.execute(sql, params)
            rows = result.fetchall()
            keys = result.keys()

        return [dict(zip(keys, row)) for row in rows]
