-- cmc_executor_run_log: Audit log for each executor invocation.
-- One row per run; updated in-place when run completes.
-- Reference DDL -- actual migration is in alembic/versions/225bf8646f03_paper_trade_executor.py

CREATE TABLE public.cmc_executor_run_log (
    -- UUID primary key (generated by Postgres)
    run_id              UUID        NOT NULL DEFAULT gen_random_uuid(),

    -- Timing
    started_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at         TIMESTAMPTZ,           -- NULL while running

    -- Scope: JSON array string of config_ids processed, e.g. "[1,2]"
    config_ids          TEXT        NOT NULL,

    -- Flags
    dry_run             BOOLEAN     NOT NULL DEFAULT FALSE,
    replay_historical   BOOLEAN     NOT NULL DEFAULT FALSE,

    -- Terminal state: updated when run finishes
    status              TEXT        NOT NULL DEFAULT 'running',

    -- Counters (updated at completion)
    signals_read        INTEGER     NOT NULL DEFAULT 0,
    orders_generated    INTEGER     NOT NULL DEFAULT 0,
    fills_processed     INTEGER     NOT NULL DEFAULT 0,
    skipped_no_delta    INTEGER     NOT NULL DEFAULT 0,

    -- Error capture
    error_message       TEXT,                  -- NULL unless status = 'failed'

    CONSTRAINT pk_cmc_executor_run_log PRIMARY KEY (run_id),

    CONSTRAINT chk_exec_run_status
        CHECK (status IN ('running', 'success', 'failed', 'stale_signal'))
);

-- Recency lookup (most recent run first)
CREATE INDEX idx_exec_run_log_ts
    ON public.cmc_executor_run_log (started_at DESC);

COMMENT ON TABLE public.cmc_executor_run_log IS
    'Audit log for paper trade executor invocations. '
    'One row per run. status transitions: running -> success | failed | stale_signal.';

COMMENT ON COLUMN public.cmc_executor_run_log.config_ids IS
    'JSON array string of dim_executor_config.config_id values processed in this run';
COMMENT ON COLUMN public.cmc_executor_run_log.skipped_no_delta IS
    'Signals read but skipped because position state has not changed since last processing';
COMMENT ON COLUMN public.cmc_executor_run_log.replay_historical IS
    'TRUE when running in historical replay mode (backfill past signals)';
