ALTER TABLE cmc_ema_multi_tf_u
    ADD COLUMN IF NOT EXISTS ema_bar        DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS d1_bar         DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS d2_bar         DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS roll_bar       BOOLEAN,
    ADD COLUMN IF NOT EXISTS d1_roll_bar    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS d2_roll_bar    DOUBLE PRECISION;